spring.application.name=cats
spring.datasource.url=jdbc:mysql://localhost:3306/cats?useSSL=false&serverTimezone=Asia/Singapore&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:Zby040315@}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false