spring.application.name=cats
spring.datasource.url=jdbc:mysql://localhost:3306/cats?useSSL=false&serverTimezone=Asia/Singapore&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:cats_app}
spring.datasource.password=${DB_PASSWORD:"your own password of your Mysql"}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
